### ISSUE TITLE
Deciding between Sparkfun and Ardusimple

### ISSUE THREAD

**Issue by sua-dev** [kmartinez/dgpstracker2#3]
Further deductions have been made with both boards, though the difference in costs still needs to be justified. 
For now, we know that both devices run using the u-centre software, though the main differences are:
- Costs: ardusimple, ~£150, sparkfun RTK, ~£238
- Power Operation: ardusimple runs only on 5V, sparkfun runs on both 3.3V and 5V.
- Both support 2 UART ports
- Configuration files can uploaded to both devices.
- More documentation and github support on sparkfun vs ardusimple
We need to make sure that we are confident with our choice of devices.

**Comment by sua-dev** [comment]
After debates on whether to consider the ardusimple or sparkfun, and a bunch of time spent debugging both boards, the sparkfun board now operates with similar operations to that of the ardusimple, though supports a 3.3V input compared to the ardusimple. Currently, it looks like we may consider using the sparkfun.

**Comment by kmartinez** [comment]
Agreed - we may save a bit of space too.
